title: "我的技术笔记"
description: "Agent、RAG、知识图谱等技术学习笔记"
baseurl: "/ObsdianValue"
url: "https://yancyuu.github.io"

# Jekyll设置
markdown: kramdown
highlighter: rouge
theme: minima

# 插件
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

# 分页设置
paginate: 10
paginate_path: "/page:num/"

# 集合设置
collections:
  pages:
    output: true
    permalink: /:name/

# 导航菜单
navigation:
  - title: 首页
    url: /
  - title: Agent
    url: /agent/
  - title: RAG  
    url: /rag/
  - title: 所有笔记
    url: /archives/
  - title: 关于
    url: /about/

# 默认设置
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "yancyuu"
  - scope:
      path: "_pages"
      type: "pages"
    values:
      layout: "page"
